# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day at 05:00 CET
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "CET"
    # Limit number of open pull requests for version updates
    open-pull-request-limit: 3

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `frontend` directory
    directory: "/frontend"
    # Check the npm registry for updates every day at 05:00 CET
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "CET"
    # Limit number of open pull requests for version updates
    open-pull-request-limit: 3

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `backend` directory
    directory: "/backend"
    # Check the npm registry for updates every day at 05:00 CET
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "CET"
    # Limit number of open pull requests for version updates
    open-pull-request-limit: 3

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `backend` directory
    directory: "/backend"
    # Check the docker registry for updates every day at 05:00 CET
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "CET"
    # Limit number of open pull requests for version updates
    open-pull-request-limit: 3
  
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `database` directory
    directory: "/database"
    # Check the docker registry for updates every day at 05:00 CET
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "CET"
    # Limit number of open pull requests for version updates
    open-pull-request-limit: 3

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `frontend` directory
    directory: "/frontend"
    # Check the docker registry for updates every day at 05:00 CET
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "CET"
    # Limit number of open pull requests for version updates
    open-pull-request-limit: 3

  # Enable version updates for Github Actions
  - package-ecosystem: "github-action"
    # Look for workflow files in the `.github/workflows` directory (happens automatically when using `root` directory as key)
    directory: "/"
    # Check the docker registry for updates every day at 05:00 CET
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "CET"
    # Limit number of open pull requests for version updates
    open-pull-request-limit: 3

