version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '4096:4096' # 4096 is the port used by express, we map this to 4096
      - '9229:9229' # debugging port
    depends_on:
      - db
    command:  ["npm", "run", "debug"]
  frontend:
    build: ./frontend
    ports:
      - '3000:3000' # 3000 is used by next, we keep using this one
      - '9119:9119' # debugging port
    depends_on:
      - backend
    command: ["npm", "run", "dev" ]
  db:
    build: ./database
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: