# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend Code Coverage

on:
  # Run on every open pull request
  pull_request:
    types: [opened, edited, reopened, synchronize]
  
jobs:
  coverage:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        working-directory: backend
