name: Lint

on:
  pull_request:
    branches:
      [ main, development ]

jobs:
  eslint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install # or yarn install
      - uses: sibiraj-s/action-eslint@v2
        with:
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true