name: lint

on:
  pull_request:
    branches: [ main, development]

jobs:
  eslint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: backend/, frontend/