name: lint

on:
  pull_request:
    branches: [ main, development]

jobs:
  eslint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: 'backend/','frontend/'