name: CI

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    name: Conventional Commits
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.0.3
