name: CI

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-for-cc:
    name: Conventional Commits
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: agenthunt/conventional-commit-checker-action@v1.0.0
